version: '3'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:3000"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: teslo_db
    volumes:
      - ./postgres:/var/lib/postgresql/data
